version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:8080"
    environment:
      - MYSQL_PROD_URL=${MYSQL_PROD_URL}
      - MYSQL_PROD_USERNAME=${MYSQL_PROD_USERNAME}
      - MYSQL_PROD_PASSWORD=${MYSQL_PROD_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_PROD_DATABASE=${MYSQL_PROD_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PROD_PASSWORD}
    ports:
      - "3306:3306"
