spring:
  sql:
    init:
      platform: local
      mode: NEVER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MY_SQL_URL}
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}
